---
title: "HW09: Wrangling II"
author: "Ryan McAnulty"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

## Loading required libraries
```{r}
library(tidyverse)
library(here)
library(knitr)
library(smatr)
```

## Sourcing my_functions.R
```{r}
source(here("scripts", "my_functions.R"))
```

## Darters in riffles
```{r}
darters <-
  read.csv(here("data", "darters.csv"))  # Importing darters.csv and naming it "darters

darters_data <-
  darters %>%                            # Saving changes as darters_data
  filter(species != "tetrazonum" &
           species != "zonale") %>%          # Removing species tetrazonum and zonale
  mutate(
    total_substrate = majsub + minsub,
    # Making total_substrate column
    riffle = ifelse(riffle == "1",         # Changing riffle values to Riffle 1 and Riffle 2
                    "Riffle 1",
                    "Riffle 2"),
    length = length * 10,
    # Changing length from centimeters to millimeters
    sex = ifelse(sex == "f",               # Changing sex to Female and Male
                 "Female",
                 "Male")
  )
```

##  Summarise data
```{r}
by_mean <-
  darters_data %>%                             # Naming summary
  group_by(species, riffle) %>%                # Grouping by species and riflles
  summarise(
    mean_length = mean(length, na.rm = TRUE),  # Setting up summary as mean of length, depth, and velocity
    mean_depth = mean(depth, na.rm = TRUE),    # na.rm = TRUE accounts for any NA
    mean_velocity = mean(velocity, na.rm = TRUE),
    .groups = "drop"
  )                                            # Dropping groups to get rid of error: summarise()` regrouping output by 'species' (override with `.groups` argument)
```

## Setting up summary in a table
```{r}
kable(by_mean)   #Tabling results
```

## Plot 1 of Darters
```{r}
ggplot(data = by_mean,
       mapping = aes(x = species, 
                     y = mean_length)) +
  stat_summary(           
    mapping = aes(x = species,    # Plotting stat summary of the length of each fish species   
                  y = length),
    fun.ymin = min,               # Plotting min length of each fish species
    fun.ymax = max,               # Plotting max of each fish species
    fun.y = median,               # Plotting median of each fish species
    data = darters_data,          #  Using data from the original data set for summary of stats
    na.rm = TRUE
  ) +
  geom_point(shape = 22,          # Using filled shape of green to show up better
             fill = "green") +    
  facet_wrap(~ riffle) +          # Setting facet warp with riffles
  labs(x = NULL,                  # Making sure x axis is not NULL 
       y = "Length (mm)") +       # Changing y axis to Length (mm)
  coord_flip()                    # Flipping the coordinates for clarity
```

The size distribution of the species "blennioides" is much wider in riffle two with on average larger fish.
There are more larger fish in riffle one than two for the other two species.

## Plot 2 of Darters
```{r}
ggplot(data = by_mean,
       mapping = aes(x = species,
                     y = mean_length)) +
  stat_summary(
    mapping = aes(x = species,    # Plotting stat summary of the length of each fish species
                  y = length),
    fun.y = median,               # Plotting median of each fish species
    geom = "point",               # Setting geom to point
    size = 2.2,                   # Setting size of point to 2.2
    data = darters_data,          # Using data from the original data set for summary of stats
    na.rm = TRUE
  ) +
  stat_summary(                   # Plotting another stat summary 
    mapping = aes(x = species, 
                  y = length),
    fun.y = mean,                 # Plotting mean of each fish species
    size = 3,                     # Setting size of points to 3
    color = "maroon",             # Setting color to maroon
    data = darters_data,          # Using original data
    na.rm = TRUE
  ) +
  geom_point(color = "gray68") +  # Remembering that ggplot plots by layers, so moving to end so that they show up, using color gray68
  facet_wrap( ~ riffle) +         # Setting facet warp with riffles
  labs(x = NULL,                  # Making sure x axis is not NULL
       y = "Length (mm)") +       # Changing y axis to Length (mm)
  coord_flip()                    # Flipping the coordinates 
```

