---
title: "HW14: Maps"
author: "Ryan McAnulty"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

## Loading necessary libraries
```{r}
library(here)
library(raster)
library(sf)
library(tidyverse)
library(ggthemes)
library(patchwork)
library(maptools)
library(ggmap)
library(marmap)
```

## US Map data
```{r}
# Outline of the 48 contiguous states
usa <-map_data(map = "state") # Tidyverse or ggplot2 must be loaded

# Outline of just Missouri
us_missouri <-map_data ( map = "state",
                         region = "missouri")

# Outline of Alabama, Florida, Mississippi, and North Carolina
us_other <-subset(x = usa,
                  subset = region %in% c("alabama",
                                         "florida",
                                         "mississippi",
                                         "north carolina"))
```

## non-Missouri layer
```{r}
ggplot() +
  geom_polygon(data = us_other,
               aes(x = long,
                   y = lat,
                   group = group),
               fill = "gray")
```

## Missouri layer added
```{r}
ggplot() +
  geom_polygon(data = us_other,
               aes(x = long,
                   y = lat,
                   group = group),
               fill = "gray") +
  geom_polygon(data = us_missouri,
               aes(x = long, y = lat,
                   group = group),
               fill = "black")
```

## US Map layer added
```{r}
ggplot() +
  geom_polygon(data = us_other,
               aes(x = long,
                   y = lat,
                   group = group),
               fill = "gray") +
  geom_polygon(data = us_missouri,
               aes(x = long, y = lat,
                   group = group),
               fill = "black") +
  geom_polygon(data = usa,
               aes(x = long,
                   y = lat,
                   group = group),
               fill = NA,
               color = "black")
```

## US Map total
```{r}
# Add the filled states first so that the black outlines of all
# states are overlaid on top.
us_map <- ggplot() +
  geom_polygon(data = us_other,
               aes(x = long,
                   y = lat,
                   group = group),
               fill = "grey") +
  geom_polygon(data = us_missouri,
               aes(x = long, y = lat,
                   group = group),
               fill = "black") +
  geom_polygon(data = usa,
               aes(x = long,
                   y = lat,
                   group = group),
               fill = NA,
               color = "black") +
  theme_map() +
  coord_fixed(1.3)
us_map
```

## Missouri
```{r}
missouri <- map_data("county", "missouri")
mo_scott <- subset(missouri, subregion %in% c("scott"))

mo_map <-ggplot() + 
  geom_polygon(data = missouri, aes(x=long, y = lat, group = group), fill = NA, color = "black") +
  geom_polygon(data = mo_scott,aes(x = long, y = lat, group = group), fill = "black") +
  theme_map() +
  coord_fixed(1.3)
mo_map
```

## US + Missouri
```{r}
us_map + mo_map + plot_layout(ncol = 2, widths = c(1.5, 1))
```

