---
title: "HW12: Dates"
author: "Ryan McAnulty"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

## Loading required libraries
```{r}
library(tidyverse)
library(here)
library(ggthemes)
library(gghighlight)
```
## From many strings to one
```{r}
beta <-                                   # Naming imported data
  read_lines(here("data",                 # Importing "beta_gliadin.txt"   
                  "beta_gliadin.txt"),
                  skip = 1)               # Skipping meta data

DNA <- beta %>%                           # Saving changes
  str_replace_all("[:digit:]",            # Removing numerals and replacing with nothing
                  "") %>%         
  str_replace_all("[:space:]",            # Removing white spaces and replacing with nothing
                  "") %>%          
  str_c(collapse = "") %>%                # Collapsing 56 strings into one
  str_to_upper()                          # Converting to all Upper case characters

DNA                                       # Displaying string to prove changes worked
```

